day72 crm 跟进记录/代码/NBcrm/NBcrm/urls.py
from django.conf.urls import url
from django.contrib import admin

from nbapp import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #首页
    url(r'^index/', views.index,name='index'),

    #注册
    url(r'^register/', views.register, name='register'),

    #登录
    url(r'^login/', views.login, name='login'),

    #验证码
    url(r'^get_valid_img/', views.get_valid_img, name='get_valid_img'),

    # 注销
    url(r'^logout/', views.logout, name='logout'),
    # url(r'^shopping/', views.shopping, name='shopping'),
    # 公户信息展示
    url(r'^customers/list/', views.CustomerView.as_view(), name='customers'),

    # 私户信息展示
    url(r'^mycustomers/', views.CustomerView.as_view(), name='mycustomers'),
    # url(r'^mycustomers/', views.mycustomers, name='mycustomers'),
    #测试分页
    url(r'^test/', views.test, name='test'),

    #添加公共客户信息路径
    url(r'^customers/add/', views.AddCustomer.as_view(), name='addcustomer'),
    #修改公共客户信息路径
    url(r'^customers/edit/(\d+)/', views.EditCustomer.as_view(), name='editcustomer'),
    #删除公共客户信息路径
    url(r'^customers/delete/(\d+)/', views.DeleteCustomer.as_view(), name='deletecustomer'),

    #跟进记录
    url(r'^consultrecord/$', views.ConsultRecordView.as_view(), name='consultrecord'),
    #添加跟进记录
    url(r'^consultrecord/add/', views.AddConsultRecordView.as_view(), name='addconsultrecord'),
    url(r'^consultrecord/edit/(\d+)/', views.AddConsultRecordView.as_view(), name='editconsultrecord'),

]

day72 crm 跟进记录/代码/NBcrm/nbapp/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser


from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
#安装:pip install django-multiselectfield,针对choices多选用的

from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)

class UserInfo(AbstractUser):
    #销售,班主任,讲师,三哥
    telephone = models.CharField(max_length=32,null=True)


class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True) #存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)

    phone = models.CharField('手机号', blank=True, null=True,max_length=32)
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)  #self指的就是自己这个表，和下面写法是一样的效果


    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices,null=True,blank=True) #多选，并且存成一个列表的格式
    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",help_text="选择客户此时的状态") #help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True)

    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True) #考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True) #销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    #用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", blank=True, null=True)

    #一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。

    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级",blank=True)


    def __str__(self):
        return self.name+":"+self.qq  #主要__str__最好是个字符串昂，不然你会遇到很多的坑，还有我们返回的这两个字段填写数据的时候必须写上数据，必然相加会报错，null类型和str类型不能相加等错误信息。


    def get_classlist(self):  #当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用

        l=[]
        for cls in self.class_list.all():
            l.append(str(cls))
        # return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂
        return ",".join(l) #纯文本，不用mark_safe也可以昂


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期") #python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True) #不一定什么时候结业，哈哈，所以可为空

    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师") #对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")

    note = models.TextField(verbose_name="跟进内容...")

    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")

    # consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records',limit_choices_to={'pk':request.user.id})
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    customer = models.ForeignKey('Customer', verbose_name='客户名称')

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)

    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)

    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")

    memo = models.TextField('备注', blank=True, null=True)

    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    school = models.ForeignKey('Campuses')  #校区表

    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


# class Enrollment(models.Model):
#     """
#     报名表
#     """
#     customer = models.ForeignKey('Customer', verbose_name='客户名称')
#
#     why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
#
#     your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
#
#     enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
#
#     memo = models.TextField('备注', blank=True, null=True)
#
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#
#     school = models.ForeignKey('Campuses')  #校区表
#
#     enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")
#
#     class Meta:
#         unique_together = ('enrolment_class', 'customer')


#
# class ConsultRecord(models.Model):
#     """
#     跟进记录表
#     """
#     customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
#
#     note = models.TextField(verbose_name="跟进内容...")
#
#     status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
#
#     consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')
#
#     date = models.DateTimeField("跟进日期", auto_now_add=True)
#
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#
#
# class Enrollment(models.Model):
#     """
#     报名表
#     """
#     customer = models.ForeignKey('Customer', verbose_name='客户名称')
#
#     why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
#
#     your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
#
#     enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
#
#     memo = models.TextField('备注', blank=True, null=True)
#
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#
#     school = models.ForeignKey('Campuses')  #校区表
#
#     enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")
#
#     class Meta:
#         unique_together = ('enrolment_class', 'customer')
#
#
# class PaymentRecord(models.Model):
#     """
#     缴费记录表
#     """
#     customer = models.ForeignKey('Customer', verbose_name="客户")
#     pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
#     paid_fee = models.IntegerField("费用数额", default=0)

day72 crm 跟进记录/代码/NBcrm/templates/addconsultrecord.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>
                添加跟进记录
                <small>Optional description</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>


        <!-- Main content -->
        <section class="content container-fluid">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <form action="" method="post" novalidate>
                            {% csrf_token %}
                            {% for field in form_obj %}
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <span class="text-danger">{{ field.errors.0 }}</span>
                                </div>


                            {% endfor %}

                            <button class="btn btn-primary pull-right">提交</button>

                        </form>
                    </div>
                </div>

            </div>

        </section>
        <!-- /.content -->
    </div>



{% endblock %}

day72 crm 跟进记录/代码/NBcrm/templates/addcustomer.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>
                添加公户客户信息
                <small>Optional description</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>


        <!-- Main content -->
        <section class="content container-fluid">
            <div class="container-fluid">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="{% url 'addcustomer' %}" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>


                    {% endfor %}

                <button class="btn btn-primary pull-right">提交</button>

                </form>
            </div>
        </div>

    </div>

        </section>
        <!-- /.content -->
    </div>





{% endblock %}

day72 crm 跟进记录/代码/NBcrm/templates/consultrecord.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>
                跟进记录
                <small>展示</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>

    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">


                        <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">
                            <select name="condition" id="" class="form-control" style="width: 100px;display: inline-block">
                                <option value="name__contains">姓名</option>
                                <option value="qq__contains">QQ</option>
                            </select>
                            <input type="text" name="wd" class="form-control" style="width: 200px;display: inline-block"> <button class="btn btn-default">搜索</button>
                        </form>
                        <a href="{% url 'addconsultrecord' %}" class="btn btn-primary pull-right">添加记录</a>

                     <form action="" method="post" >
                            {% csrf_token %}
                            <select name="action" id="" class="form-control" style="width: 200px;display: inline-block">
                                <option value="batch_delete">批量删除</option>
                                <option value="batch_update">批量更新跟进记录</option>



                            </select>
                            <button class="btn btn-danger" style="vertical-align: 1px;">go</button>


                    <!-- /.box-header -->
                        <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="choose">
                                </th>
                                <th>序号</th>
                                <th>所咨询客户</th>
                                <th>跟进内容</th>
                                <th>跟进状态</th>
                                <th>跟进人</th>
                                <th>跟进日期</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for record in all_records %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ record.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ record.customer }}</td>
                                        <td>{{ record.note }}</td>
                                        <td>{{ record.get_status_display }}</td>
                                        <td>{{ record.consultant.username }}</td>
                                        <td>{{ record.date|date:'Y-m-d' }}</td>

                                        <td>
                                            <a href="{% url 'editconsultrecord' record.pk %}" class="btn btn-warning btn-xs">编辑</a>
                                            <a href="{% url 'deletecustomer' record.pk %}" class="btn btn-danger btn-xs">删除</a>
                                        </td>
{#                                        <td>{{ customer.get_classlist }}</td>#}
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                     </form>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

    {{ ret_html|safe }}
    </div>
{% endblock %}

{% block js %}
    <script>
        $('#choose').click(function(){
        var status = $(this).prop('checked');
        $('[name=selected_id]').prop('checked',status);
{#        if (status === true){#}
{#            $('[name=selected_id]').prop('checked',true);#}
{##}
{#        }#}
{#        else{#}
{#            $('[name=selected_id]').prop('checked',false);#}
{#        }#}
    })
    </script>

{% endblock %}

day72 crm 跟进记录/代码/NBcrm/templates/customers.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>
                {% if flag %}
                    我的客户信息
                {% else %}
                    公共客户信息
                {% endif %}
                <small>展示</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>

    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">


                        <form action="" method="get" class="pull-right" style="width: 400px;display: inline-block">
                            <select name="condition" id="" class="form-control" style="width: 100px;display: inline-block">
                                <option value="name__contains">姓名</option>
                                <option value="qq__contains">QQ</option>
                            </select>
                            <input type="text" name="wd" class="form-control" style="width: 200px;display: inline-block"> <button class="btn btn-default">搜索</button>
                        </form>
                        <a href="{% url 'addcustomer' %}" class="btn btn-primary pull-right">添加记录</a>

                     <form action="" method="post" >
                            {% csrf_token %}
                            <select name="action" id="" class="form-control" style="width: 200px;display: inline-block">
                                <option value="batch_delete">批量删除</option>
                                <option value="batch_update">批量更新客户状态</option>
                            {% if flag %}
                                <option value="batch_reverse_sg">私户转公户</option>
                            {% else %}
                                <option value="batch_reverse_gs">公户转私户</option>
                            {% endif %}

{#                            <option value="batch_reverse_sg">私户转公户</option>#}

                            </select>
                            <button class="btn btn-danger" style="vertical-align: 1px;">go</button>


                    <!-- /.box-header -->
                        <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="choose">
                                </th>
                                <th>序号</th>
                                <th>qq</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>客户来源</th>
{#                                <th>转介绍自学员</th>#}
                                <th>咨询课程</th>
                                <th>选择客户此时的状态</th>
                                <th>销售</th>
                                <th>操作</th>
{#                                <th>已报班级</th>#}
                            </tr>
                            </thead>
                            <tbody>
                                {% for customer in all_customers %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ customer.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ customer.qq }}</td>
                                        <td>{{ customer.name }}</td>
                                        <td>{{ customer.get_sex_display }}</td>
                                        <td>{{ customer.get_source_display }}</td>
{#                                        <td>{{ customer.introduce_from.name|default:'暂无' }}</td>#}
                                        <td>{{ customer.course }}</td>
                                        <td>{{ customer.get_status_display }}</td>
                                        <td>{{ customer.consultant.username|default:'暂无' }}</td>
                                        <td>
                                            <a href="{% url 'editcustomer' customer.pk %}" class="btn btn-warning btn-xs">编辑</a>
                                            <a href="{% url 'deletecustomer' customer.pk %}" class="btn btn-danger btn-xs">删除</a>
                                        </td>
{#                                        <td>{{ customer.get_classlist }}</td>#}
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                     </form>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

    {{ ret_html|safe }}
    </div>
{% endblock %}

{% block js %}
    <script>
        $('#choose').click(function(){
        var status = $(this).prop('checked');
        $('[name=selected_id]').prop('checked',status);
{#        if (status === true){#}
{#            $('[name=selected_id]').prop('checked',true);#}
{##}
{#        }#}
{#        else{#}
{#            $('[name=selected_id]').prop('checked',false);#}
{#        }#}
    })
    </script>

{% endblock %}

day72 crm 跟进记录/代码/NBcrm/templates/editcustomer.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>


                    {% endfor %}

                <button class="btn btn-primary pull-right">提交</button>

                </form>
            </div>
        </div>

    </div>


{% endblock %}

day72 crm 跟进记录/代码/NBcrm/templates/index.html
{% extends 'base.html' %}

day72 crm 跟进记录/代码/NBcrm/templates/mycustomers.html
{% extends 'base.html' %}

{% block content %}

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>
                我的客户信息
                <small>展示</small>
            </h1>

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>

    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">

                        <form action="" method="get" class="pull-right" style="width: 400px">
                            <select name="condition" id="" class="form-control" style="width: 100px;display: inline-block">
                                <option value="name__contains">姓名</option>
                                <option value="qq__contains">QQ</option>
                            </select>
                            <input type="text" name="wd" class="form-control" style="width: 200px;display: inline-block"> <button class="btn btn-default">搜索</button>
                        </form>
                        <a href="{% url 'addcustomer' %}" class="btn btn-primary pull-right">添加记录</a>

                        <form action="{% url 'customers' %}" method="post">
                            {% csrf_token %}
                            <select name="action" id="" class="form-control" style="width: 200px;display: inline-block">
                                <option value="batch_delete">批量删除</option>
                                <option value="batch_update">批量更新客户状态</option>
                            <option value="batch_reverse_gs">公户转私户</option>
{#                            <option value="batch_reverse_sg">私户转公户</option>#}

                            </select>
                            <button class="btn btn-danger" style="vertical-align: 1px;">go</button>


                    <!-- /.box-header -->
                        <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="choose">
                                </th>
                                <th>序号</th>
                                <th>qq</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>客户来源</th>
{#                                <th>转介绍自学员</th>#}
                                <th>咨询课程</th>
                                <th>选择客户此时的状态</th>
                                <th>销售</th>
                                <th>操作</th>
{#                                <th>已报班级</th>#}
                            </tr>
                            </thead>
                            <tbody>
                                {% for customer in my_customers %}
                                    <tr>
                                        <td><input type="checkbox" name="selected_id" value="{{ customer.pk }}"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ customer.qq }}</td>
                                        <td>{{ customer.name }}</td>
                                        <td>{{ customer.get_sex_display }}</td>
                                        <td>{{ customer.get_source_display }}</td>
{#                                        <td>{{ customer.introduce_from.name|default:'暂无' }}</td>#}
                                        <td>{{ customer.course }}</td>
                                        <td>{{ customer.get_status_display }}</td>
                                        <td>{{ customer.consultant.username|default:'暂无' }}</td>
                                        <td>
                                            <a href="{% url 'editcustomer' customer.pk %}" class="btn btn-warning btn-xs">编辑</a>
                                            <a href="{% url 'deletecustomer' customer.pk %}" class="btn btn-danger btn-xs">删除</a>
                                        </td>
{#                                        <td>{{ customer.get_classlist }}</td>#}
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                     </form>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

    {{ ret_html|safe }}
    </div>



{% endblock %}

day72 crm 跟进记录/代码/NBcrm/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<h1>这是注册页面</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="{% url 'register' %}" method="post" novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="text-danger">{{ field.errors.0 }}</span>
                    </div>

                {% endfor %}

                <input type="submit" class="btn btn-success pull-right" value="注册">

            </form>

        </div>
    </div>

</div>


<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script>


</script>
</body>
</html>